### ISSUE TITLE
Support 22.04

### ISSUE THREAD

**Issue by doughnet** [monsn0/omada-installer#1]
ERROR: Script only supports Ubuntu 16.04, 18.04 or 20.04!

**Comment by monsn0** [comment]
Officially, Omada SDN is not supported on Ubuntu 22.04 as of yet and is most likely due to the lack of a MongoDB 4 package on 22.04. There may be ways around this by building from source for example, however, the scope of this script is to stay within officially supported methods only.

Once TP-Link supports or at least all dependencies are supported on Ubuntu 22.04, I'll return to this and update the script.

**Comment by doughnet** [comment]
Thank you.  I was able to install it with Ubuntu 22.04 just fine.  been running since last night without issues.
