### ISSUE TITLE
Add support for MongoDB 7

### ISSUE THREAD

**Issue by jkoch2** [monsn0/omada-installer#11]
MongoDB 7 is supported by Ubuntu 22.04 and Omada Controller 5.14.20. No need to install MongoDB 4.4 on 22.04 any more 😃

**Comment by monsn0** [comment]
Nice! Thanks for the heads up. I'll work getting this updated for mongodb 7

**Comment by jkoch2** [comment]
Just wanted to add that there will need to be logic in the script to check for an AVX compatible CPU.

**Comment by monsn0** [comment]
Ah yes, I remember reading about the AVX requirement starting in MongoDB 5 but dismissed it due to only using 4.4. In addition, AVX has been supported on CPUs from around 2011 onwards.

However, I do understand the possibility of attempting to run the script on older hardware so I'll be sure to add that logic in. Hopefully, there aren't too many of these cases out there 😅
